### ISSUE TITLE
Plan for specs2 v5.0.0?

### ISSUE THREAD

**Issue by armanbilge** [typelevel/discipline-specs2#192]
It's currently in the RC stage, would be awesome to start testing it:
https://github.com/etorreborre/specs2/releases

The tricky thing is it looks like 5.0.0 is Scala 3 only. At first I was going to propose (if it's not insane) we publish the Scala 3 build of discipline-specs2 against specs2 v5 and continue publishing the Scala 2 build against specs2 v4, but it seems this library has already published for Scala 3 using `for3Use2_13`. So a major version bump looks inevitable.

**Comment by djspiewak** [comment]
> So a major version bump looks inevitable.

IMO that's not a problem. That's the whole point to these test framework compatibility libraries being in separate repos.

**Comment by armanbilge** [comment]
I don't think it will really help us actually, since specs5 is Scala 3 only. Unless you want to publish the same module/artifact with different dependencies (and therefore different sources) for 2.x/3?

**Comment by rossabaker** [comment]
The next major version could be for Scala 3 only, just like Specs2 itself.  That's fine as long as there's never another major version of Discipline that needs Specs2+Scala 2 support.

**Comment by etorreborre** [comment]
Here is a PR: https://github.com/typelevel/discipline-specs2/pull/207
