### ISSUE TITLE
Snapshot publish failed

### ISSUE THREAD

**Issue by armanbilge** [typelevel/discipline-specs2#311]
https://github.com/typelevel/discipline-specs2/runs/4873252215?check_suite_focus=true

```
[error] java.net.ProtocolException: Server redirected too many  times (20)
```

Other projects are publishing fine so I assume its something specific to this repo 🤔 

I think I've seen this error when the sonatype credentials are for the wrong host. How are yours set up?

**Comment by vasilmkd** [comment]
I don't know actually. It's possible there are no credentials set up for the project. I believe it's only ever been released locally. I also don't have the rights to change it.

**Comment by armanbilge** [comment]
Ah :) I'm actually hoping to get org-wide credentials installed so that individual repos don't have to worry about this.

**Comment by armanbilge** [comment]
CI release can be disabled like so:
```scala
ThisBuild / tlCiReleaseTags := false
ThisBuild / tlCiReleaseBranches := Seq.empty
```

**Comment by vasilmkd** [comment]
Thanks!

**Comment by armanbilge** [comment]
https://oss.sonatype.org/content/repositories/snapshots/org/typelevel/discipline-specs2_2.13/1.4-b96b2d3-SNAPSHOT/
