### ISSUE TITLE
Making `2.x` the new `main`

### ISSUE THREAD

**Issue by TonioGela** [typelevel/discipline-specs2#579]
Given that (to the best of my understanding) spec2 since 5.x is releasing just Scala 3 artifacts and that we have 2.x that is moving accordinly, shouldn't we simply "swap" the branches, release a last 1.x and go on with 2.x as the new default?

We should also stop Scala Steward from attempting updates [like this](https://github.com/typelevel/discipline-specs2/pull/577) as they'll never be possible again in the future.

**Comment by armanbilge** [comment]
> since 5.x is releasing just Scala 3 artifacts

This is exactly the problem which is why Cats Effect is pinned to specs2 4.x series. This is also why Eric is continuing to publish specs2 4.x releases. At the moment for us specs2 4.x is a lot more important than 5.x.

> release a last 1.x

So what happens to Cats Effect and everyone depending on 1.x? :)

**Comment by TonioGela** [comment]
Okay, everything seems reasonable. Maybe we should simply remove the 2.12 and 2.13 support in the `2.x` branch then?

**Comment by armanbilge** [comment]
> Maybe we should simply remove the 2.12 and 2.13 support in the `2.x` branch then?

That's the thing, there is no support for 2.12 or 2.13 in the 2.x branch :) that's why we cannot use it in Cats Effect.

https://github.com/typelevel/discipline-specs2/blob/614f8d9303c3303ecd2d9313f9597308a968c83d/build.sbt#L12

**Comment by TonioGela** [comment]
Okay, I was clearly confused (or I was doing too many things at once) when I opened this issue
